version: '3.3'

services:
  web:
    build:
      context: .
    image: findflix:latest
    restart: always
    environment:
      TMBD_API_BASE_URL: ${TMDB_API_BASE_URL}
      NEXT_PUBLIC_TMDB_IMAGE_BASE_URL: ${NEXT_PUBLIC_TMDB_IMAGE_BASE_URL}
      TMDB_API_KEY: ${TMDB_API_KEY}
      TMDB_FAVOURITES_LIST_ID: ${TMDB_FAVOURITES_LIST_ID}
    ports:
      - 3000:3000
    volumes:
      - .:/app
